spring.application.name=accountbook
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://db:5432/antibudget
spring.datasource.username=antibudget
spring.datasource.password=antibudget123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
